---
title: "ggplottutorial"
author: "brockad"
date: "2020-09-15"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction
Learning how to explore data and tell stories using ggplot2.

Load packages:
```{r Package Loading}
library(tidyverse)
library(ggplot2)
library(cowplot)
library(ggrepel)
library(htmlwidgets)
library(plotly)
```

Load data for data visualization:
```{r Loading Data}
dogs <- read_csv(file = "data/dogs.csv")

nrow(dogs)
ncol(dogs)
names(dogs)
head(dogs)
tail(dogs)
summary(dogs)
class(dogs$aod)
class(dogs$height)
class(dogs$weight)
class(dogs$shortcoat)

unique(dogs$shortcoat)
```

Starting to plot data:
```{r Initial Plotting}
plot(dogs$weight, dogs$aod)
#It appears that smaller dogs tend to live longer than larger dogs.

p1 <- ggplot(dogs, aes_string(x = "weight", y = "aod")) #generate plotting object
p1 <- ggplot_add(geom_point(), p1) #Adds points to p1
##p1 #Shows plot

#You can add multiple layers with a single call of ggplot using "+"
p1 <- ggplot(dogs, aes_string(x = "weight", y = "aod")) + 
  geom_point() + scale_x_continuous(breaks = seq(0,160,40)) +
  labs(x = "body weight (lbs)", y = "longevity (years)", title = "Longevity of dogs versus weight") + theme_cowplot()
p1

#Add fit line observed and previous fitting
fit <- lm(aod ~ weight,dogs)
summary(fit)
coef(fit)
p2 <- p1 + geom_abline(color = "skyblue", linetype = "dashed", 
                       intercept = coef(fit)[1], slope = coef(fit)[2]) +
  geom_abline(color = "tomato", linetype = "dashed", intercept = 13, slope = -1/28)

p2

p3 <- p2 + geom_text_repel(mapping = aes_string(label = "breed"), 
                           color = "gainsboro")

p3

#Adding color to the plot
#Factoring to make discrete colors for plot
dogs$shortcoat <- factor(dogs$shortcoat)

p4 <- ggplot(dogs, aes_string(x = "weight", y = "aod", label = "breed",
                              color = "shortcoat")) +
  geom_point() + theme_cowplot()

p5 <- p4 + scale_color_manual(values = c("firebrick", "tomato"),
                              na.value = "grey")

p5 + scale_x_continuous(trans = "sqrt")

#Saving a plot
#ggsave("dogs.pdf", p5, height = 4, width = 4.5)
```




